package fG.Enum;

public enum WhatsappMessageType {
    ADMIN_MEETING_BOOKED,
    ADMIN_USER_REGISTRATION,
    ADMIN_MEETING_COMPLETION,
    ADMIN_MEETING_STATUS_PENDING,
    ADMIN_MEETING_STARTS_15MIN,
    L_REG,
    L_MEET_CREATE,
    L_MEET_CONFIRM,
    L_MEET_E_START,
    L_MEET_REMIND_15,
    E_PROFILE_VERIFY,
    E_MEET_REQUEST,
    E_MEET_REQUEST_REMIND_180,
    E_MEET_REMIND_15
}
