package fG.Enum;

public enum WhatsappMessageType {
    ADMIN_MEETING_BOOKED,
    ADMIN_USER_REGISTRATION,
    ADMIN_MEETING_COMPLETION,
    ADMIN_MEETING_STATUS_PENDING,
    ADMIN_MEETING_STARTS_15MIN
}
